### PR TITLE
New Plugin “Remote"

### PR DESCRIPTION
**Pull request by johnno1962**
For end-to-end testing and generally not having to pick up your device.

### CODE REVIEW

**Comment by jurre** [comment]
This is really awesome @johnno1962!

**Comment by jurre** [comment]
Whoops, looks like you've added it as a file template instead of a plugin, could you move it to plugins?

**Comment by johnno1962** [comment]
Do’h sorry about that… moved to plugins.

**Comment by jurre** [comment]
Cool, thanks!

**Pull request merged**
