### PR TITLE
Add EditorConfig plugin

### PR DESCRIPTION
**Pull request by MarcoSero**

### CODE REVIEW

**Comment by jurre** [comment]
Oh, nice one! Can't believe we didn't have this in Alcatraz yet! (waiting for travis to merge)

**Comment by MarcoSero** [comment]
Is there anything that still needs to be done in order to merge this?

**Comment by jurre** [comment]
No, thanks!

**Comment by MarcoSero** [comment]
:sparkles:

**Comment by supermarin** [comment]
Woa @MarcoSero :100: !!

**Pull request merged**
