### PR TITLE
Added MMJiOSTemplates

### PR DESCRIPTION
**Pull request by mihaelamj**
Added iOS project templates to replace the missing Empty Application template.

### CODE REVIEW

**Comment by jurre** [comment]
Hey, you added it as a plugin, could you add it as a template instead? :)

**Comment by mihaelamj** [comment]
Hi Sorry.
I will fix that.

Thanks.

**Comment by mihaelamj** [comment]
I fixed it.

**Comment by jurre** [comment]
Thanks!

**Pull request merged**
