### PR TITLE
add AxeMode plugin by @alloy

### PR DESCRIPTION
**Pull request by jurre**
@alloy hope you don't mind ^^

### CODE REVIEW

**Comment by alloy** [comment]
Hey @jurre, thanks for taking the time to create this PR and, I assume, finding the plugin helpful :)

I do think that [this](https://github.com/alloy/AxeMode/issues/1) TODO really needs to be implemented first, though, as it might be annoying for people if it would perform a different action than the one they initially triggered.

**Comment by jurre** [comment]
Makes sense, I'll hold off merging this then!

**Comment by alloy** [comment]
@jurre It’s good to go now!

**Comment by jurre** [comment]
Awesome, thanks!

**Comment by alloy** [comment]
Thanks for adding!

**Comment by orta** [comment]
:tada:

**Pull request merged**
