### PR TITLE
Add Multiplex plugin

### PR DESCRIPTION
**Pull request by kolinkrewinkel**
First time doing this, hopefully it’s right! ^_^

### CODE REVIEW

**Comment by jurre** [comment]
You've added it as a file template :) there are top level keys in the json file and it looks like this should go under "plugins"

**Comment by kolinkrewinkel** [comment]
Whoops... >_< Should be good now, I think.

**Comment by jurre** [comment]
Ah yeah, I just merged another PR so could you please rebase this against master?

**Comment by kolinkrewinkel** [comment]
Rebased

**Comment by jurre** [comment]
Awesome, thnx!

**Pull request merged**
